FROM 192.168.50.252:65000/python:3.7.7-alpine

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY plugin.py ./

ENTRYPOINT ["python", "/usr/src/app/plugin.py"]
